In [1]:
import larch
import numpy as np

In [2]:
np.set_printoptions(
    edgeitems=10, 
    linewidth=200, 
    formatter=dict(float=lambda x: "{:<9.4g}".format(x))
)

In [3]:
larch.Model

larch.model.model.Model

In [4]:
m = larch.example(22)

In [5]:
m.graph

In [6]:
m.estimate()

value  initvalue  nullvalue  minimum  maximum  \
ASC_BIKE            -1.201235        0.0        0.0     -inf      inf   
ASC_SR2             -1.325025        0.0        0.0     -inf      inf   
ASC_SR3             -2.505543        0.0        0.0     -inf      inf   
ASC_TRANSIT         -0.403523        0.0        0.0     -inf      inf   
ASC_WALK             0.345445        0.0        0.0     -inf      inf   
costbyincome        -0.038615        0.0        0.0     -inf      inf   
hhinc#4             -0.003931        0.0        0.0     -inf      inf   
hhinc#5             -0.010045        0.0        0.0     -inf      inf   
hhinc#6             -0.006207        0.0        0.0     -inf      inf   
motorized_ovtbydist -0.113798        0.0        0.0     -inf      inf   
motorized_time      -0.014523        0.0        0.0     -inf      inf   
mu_motor             0.725787        1.0        1.0    0.001      1.0   
mu_nonmotor          0.768938        1.0        1.0    0.001      1.0   
nonmotorized_time   -0.046215        0.0        0.0     -inf      inf   
vehbywrk_BIKE       -0.734800        0.0        0.0     -inf      inf   
vehbywrk_SR         -0.225671        0.0        0.0     -inf      inf   
vehbywrk_TRANSIT    -0.707055        0.0        0.0     -inf      inf   
vehbywrk_WALK       -0.763868        0.0        0.0     -inf      inf   
wkcbd_BIKE           0.407703        0.0        0.0     -inf      inf   
wkcbd_SR2            0.193141        0.0        0.0     -inf      inf   
wkcbd_SR3            0.780955        0.0        0.0     -inf      inf   
wkcbd_TRANSIT        0.921274        0.0        0.0     -inf      inf   
wkcbd_WALK           0.114114        0.0        0.0     -inf      inf   
wkempden_BIKE        0.001674        0.0        0.0     -inf      inf   
wkempden_SR2         0.001149        0.0        0.0     -inf      inf   
wkempden_SR3         0.001638        0.0        0.0     -inf      inf   
wkempden_TRANSIT     0.002237        0.0        0.0     -inf      inf   
wkempden_WALK        0.002170        0.0        0.0     -inf      inf   

                     holdfast note      best  
ASC_BIKE                    0      -1.201235  
ASC_SR2                     0      -1.325025  
ASC_SR3                     0      -2.505543  
ASC_TRANSIT                 0      -0.403523  
ASC_WALK                    0       0.345445  
costbyincome                0      -0.038615  
hhinc#4                     0      -0.003931  
hhinc#5                     0      -0.010045  
hhinc#6                     0      -0.006207  
motorized_ovtbydist         0      -0.113798  
motorized_time              0      -0.014523  
mu_motor                    0       0.725787  
mu_nonmotor                 0       0.768938  
nonmotorized_time           0      -0.046215  
vehbywrk_BIKE               0      -0.734800  
vehbywrk_SR                 0      -0.225671  
vehbywrk_TRANSIT            0      -0.707055  
vehbywrk_WALK               0      -0.763868  
wkcbd_BIKE                  0       0.407703  
wkcbd_SR2                   0       0.193141  
wkcbd_SR3                   0       0.780955  
wkcbd_TRANSIT               0       0.921274  
wkcbd_WALK                  0       0.114114  
wkempden_BIKE               0       0.001674  
wkempden_SR2                0       0.001149  
wkempden_SR3                0       0.001638  
wkempden_TRANSIT            0       0.002237  
wkempden_WALK               0       0.002170

/Users/jeffnewman/opt/anaconda3/envs/garage38/lib/python3.8/site-packages/numpy/core/_methods.py:47: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/Users/jeffnewman/opt/anaconda3/envs/garage38/lib/python3.8/site-packages/numpy/core/_methods.py:47: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/Users/jeffnewman/opt/anaconda3/envs/garage38/lib/python3.8/site-packages/numpy/core/_methods.py:47: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)


┣                x: ASC_BIKE              -1.201235
┃                   ASC_SR2               -1.325025
┃                   ASC_SR3               -2.505543
┃                   ASC_TRANSIT           -0.403523
┃                   ASC_WALK               0.345445
┃                   costbyincome          -0.038615
┃                   hhinc#4               -0.003931
┃                   hhinc#5               -0.010045
┃                   hhinc#6               -0.006207
┃                   motorized_ovtbydist   -0.113798
┃                   motorized_time        -0.014523
┃                   mu_motor               0.725787
┃                   mu_nonmotor            0.768938
┃                   nonmotorized_time     -0.046215
┃                   vehbywrk_BIKE         -0.734800
┃                   vehbywrk_SR           -0.225671
┃                   vehbywrk_TRANSIT      -0.707055
┃                   vehbywrk_WALK         -0.763868
┃                   wkcbd_BIKE             0.407703
┃                   wkcbd_SR2              0.193141
┃                   wkcbd_SR3              0.780955
┃                   wkcbd_TRANSIT          0.921274
┃                   wkcbd_WALK             0.114114
┃                   wkempden_BIKE          0.001674
┃                   wkempden_SR2           0.001149
┃                   wkempden_SR3           0.001638
┃                   wkempden_TRANSIT       0.002237
┃                   wkempden_WALK          0.002170
┃                   dtype: float64
┣          loglike: -3441.6725272475805
┣        d_loglike: ASC_BIKE               0.001096
┃                   ASC_SR2                0.002816
┃                   ASC_SR3               -0.000161
┃                   ASC_TRANSIT           -0.000941
┃                   ASC_WALK              -0.001746
┃                   costbyincome          -0.018781
┃                   hhinc#4                0.042637
┃                   hhinc#5                0.054682
┃                   hhinc#6               -0.198514
┃                   motorized_ovtbydist   -0.004421
┃                   motorized_time        -0.023584
┃                   mu_motor              -0.001409
┃                   mu_nonmotor            0.000154
┃                   nonmotorized_time     -0.026345
┃                   vehbywrk_BIKE          0.001556
┃                   vehbywrk_SR            0.005059
┃                   vehbywrk_TRANSIT      -0.001194
┃                   vehbywrk_WALK         -0.003497
┃                   wkcbd_BIKE             0.000275
┃                   wkcbd_SR2              0.000126
┃                   wkcbd_SR3              0.000172
┃                   wkcbd_TRANSIT          0.001999
┃                   wkcbd_WALK             0.000515
┃                   wkempden_BIKE          0.097725
┃                   wkempden_SR2           0.228821
┃                   wkempden_SR3           0.132721
┃                   wkempden_TRANSIT      -0.099216
┃                   wkempden_WALK          0.140379
┃                   dtype: float64
┣              nit: 48
┣             nfev: 162
┣             njev: 48
┣           status: 0
┣          message: 'Optimization terminated successfully'
┣          success: True
┣     elapsed_time: datetime.timedelta(seconds=8, microseconds=812012)
┣           method: 'slsqp'
┣          n_cases: 5029
┣ iteration_number: 48
┣          logloss: 0.6843651873628118

In [7]:
m.probability().shape

(5029, 6)

In [8]:
m.logsums()

array([-0.2752  , 0.5206   , -0.1259  , 0.1256   , -0.5672  , -0.273   , -0.114   , -0.3996  , -0.1453  , -0.1819  , ..., -0.2065  , -0.5604  , -0.9356  , -0.153   , -0.2931  , -0.8378  , -0.3106  ,
       -0.3426  , -0.3277  , -0.7013  ])

In [9]:
u = m.utility().copy()

In [10]:
u.shape

(5029, 9)

In [11]:
m.probability()[:16]

array([[0.9445   , 0.04172  , 0.00805  , 0.003812 , 0.001929 , 0        ],
       [0.05883  , 0.0498   , 0.06423  , 0.8111   , 0.01606  , 0        ],
       [0.6012   , 0.1159   , 0.0517   , 0.2312   , 0        , 0        ],
       [0.2344   , 0.07462  , 0.06167  , 0.6293   , 0        , 0        ],
       [0        , 0.2567   , 0.1103   , 0.5735   , 0.0595   , 0        ],
       [0        , 0.2073   , 0.08987  , 0.5458   , 0.09228  , 0.06476  ],
       [0.7321   , 0.1107   , 0.04866  , 0.01129  , 0.07776  , 0.01948  ],
       [0.8282   , 0.1044   , 0.02118  , 0.03886  , 0.007348 , 0        ],
       [0.8391   , 0.08951  , 0.03872  , 0.03271  , 0        , 0        ],
       [0.6637   , 0.1033   , 0.04596  , 0.1871   , 0        , 0        ],
       [0.07606  , 0.0445   , 0.04475  , 0.8206   , 0.01407  , 0        ],
       [0.9609   , 0.03155  , 0.006124 , 0.001442 , 0        , 0        ],
       [0.8142   , 0.09724  , 0.04225  , 0.04636  , 0        , 0        ],
       [0.7823   , 0.0934

In [12]:
p = m.probability_from_utility(u)

In [13]:
p

array([[0.9445   , 0.04172  , 0.00805  , 0.003812 , 0.001929 , 0        , 0.9981   , 0.001929 , 1        ],
       [0.05883  , 0.0498   , 0.06423  , 0.8111   , 0.01606  , 0        , 0.9839   , 0.01606  , 1        ],
       [0.6012   , 0.1159   , 0.0517   , 0.2312   , 0        , 0        , 1        , 0        , 1        ],
       [0.2344   , 0.07462  , 0.06167  , 0.6293   , 0        , 0        , 1        , 0        , 1        ],
       [0        , 0.2567   , 0.1103   , 0.5735   , 0.0595   , 0        , 0.9405   , 0.0595   , 1        ],
       [0        , 0.2073   , 0.08987  , 0.5458   , 0.09228  , 0.06476  , 0.843    , 0.157    , 1        ],
       [0.7321   , 0.1107   , 0.04866  , 0.01129  , 0.07776  , 0.01948  , 0.9028   , 0.09723  , 1        ],
       [0.8282   , 0.1044   , 0.02118  , 0.03886  , 0.007348 , 0        , 0.9927   , 0.007348 , 1        ],
       [0.8391   , 0.08951  , 0.03872  , 0.03271  , 0        , 0        , 1        , 0        , 1        ],
       [0.6637   , 0.1033   

In [14]:
u.shape

(5029, 9)

In [15]:
m.probability_from_utility(np.zeros([1000000,9]))

array([[0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    , 0.154    , 0.154    , 0.1919   , 0.1919   , 0.6161   , 0.3839   , 1        ],
       [0.154    , 0.154    

In [16]:
m2 = larch.Model(graph=m.graph)#.probability_from_utility(np.zeros([1000000,9]))

In [17]:
m2.graph

In [18]:
u = np.zeros([10,9])

In [19]:
m2.probability_from_utility(u)

array([[0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.1667   , 0.6667   , 0.3333   , 1        ],
       [0.1667   , 0.1667   

In [20]:
m2.logsums_from_utility(u)

array([1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    ])

In [21]:
u[:,-1]

array([1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    , 1.792    ])

In [24]:
import time
pre_time = time.time()
time.sleep(1)
(f"assign_variables in {(time.time()-pre_time)*1000:.1f}: ")


'assign_variables in 1004.2: '

In [59]:
import pandas as pd
import numpy as np
from activitysim.core.util import reindex

In [60]:
#one = pd.Series([11,22,33,44,55], index=[111,222,333,444,555])
one = pd.Series(np.arange(5000)*11, index=np.arange(5000)*111)

In [61]:
#two = pd.Series([111,222,333,444,555,444,111], index=[21,22,23,24,25,26,27])

In [62]:
two = pd.Series(
    np.random.choice(np.arange(5000)*111, 15000), 
    index=np.arange(15000)+720000000
)

In [63]:
%timeit reindex(one,two)

1.57 ms ± 16.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
def reindex3(a,b):
    s = a.loc[b].reset_index(drop=True)
    s.index = b.index
    return s

In [97]:
def reindex4(series1, series2):
    #return pd.Series(series1.loc[series2.values].values, index=None)
    return pd.Series(series1.reindex(series2.values).values, index=getattr(series2,'index', series2))


In [93]:
pd.RangeIndex(6).to_frame(name='left')

left
0     0
1     1
2     2
3     3
4     4
5     5

In [87]:
%timeit reindex(one,two)

1.58 ms ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [90]:
%timeit reindex4(one,two)

266 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [72]:
reindex4(one,two)

0        34683
1         5577
2         1639
3         9988
4        48235
         ...  
14995    20933
14996    42856
14997    13266
14998    34518
14999    45859
Length: 15000, dtype: int64

In [73]:
reindex(one,two)

720000000    34683
720000001     5577
720000002     1639
720000003     9988
720000004    48235
             ...  
720014995    20933
720014996    42856
720014997    13266
720014998    34518
720014999    45859
Name: right, Length: 15000, dtype: int64

In [98]:
two1 = pd.Series(
    [111, 29387498], 
    index=[55,56]
)

In [99]:
reindex4(one,pd.RangeIndex(108,114))

108     NaN
109     NaN
110     NaN
111    11.0
112     NaN
113     NaN
dtype: float64

In [95]:
one

0             0
111          11
222          22
333          33
444          44
          ...  
554445    54945
554556    54956
554667    54967
554778    54978
554889    54989
Length: 5000, dtype: int64

In [80]:
pd.Series(one.reindex(two1).values, index=two1.index)


55    11.0
56     NaN
dtype: float64